# Generated by Django 5.2.2 on 2025-06-10 08:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_remove_notes_author_alter_notes_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 10, 18, 25, 28, 587760)),
        ),
    ]
