# Generated by Django 5.2.2 on 2025-06-10 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_alter_notes_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='content',
            field=models.TextField(default='', max_length=1200),
        ),
        migrations.AlterField(
            model_name='notes',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 10, 18, 40, 46, 879595)),
        ),
        migrations.AlterField(
            model_name='notes',
            name='description',
            field=models.CharField(max_length=20),
        ),
    ]
