# Generated by Django 5.2.2 on 2025-06-11 02:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_notes_content_alter_notes_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 11, 12, 40, 26, 547073)),
        ),
    ]
