# Generated by Django 5.2.2 on 2025-06-11 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_alter_notes_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='notes',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='notes',
            name='description',
            field=models.CharField(max_length=50),
        ),
    ]
